# Generated by Django 5.0.7 on 2024-08-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_current_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='guest_count',
            field=models.IntegerField(default=0),
        ),
    ]
